/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.moje.zavrsnirad.view;

import hr.moje.zavrsnirad.controller.ObradaClan;
import hr.moje.zavrsnirad.controller.ObradaDuzina;
import hr.moje.zavrsnirad.controller.ObradaKolo;
import hr.moje.zavrsnirad.controller.ObradaPrisutnost;
import hr.moje.zavrsnirad.controller.ObradaRezultat;
import hr.moje.zavrsnirad.model.Clan;
import hr.moje.zavrsnirad.model.Duzina;
import hr.moje.zavrsnirad.model.Kolo;
import hr.moje.zavrsnirad.model.Rezultat;
import hr.moje.zavrsnirad.util.Pomocno;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;

/**
 *
 * @author LasovicaPC
 */
public class ViewRezultat extends javax.swing.JFrame {

    private final ObradaKolo obradaKolo = new ObradaKolo();
    private final ObradaRezultat obradaRezultat = new ObradaRezultat();
    private final ObradaDuzina obradaDuzina = new ObradaDuzina();
    /**
     * Creates new form ViewRezultat
     */
    public ViewRezultat() {
        initComponents();
        ucitaj();
    }
    
    private void ucitaj() {
        DefaultListModel<Kolo> modelKolo = new DefaultListModel<>();
        obradaKolo.getPodaci().forEach(s -> modelKolo.addElement(s));
        lstKolo.setModel(modelKolo);
        
        DefaultListModel<Duzina> modelDuzina = new DefaultListModel<>();
        obradaDuzina.getPodaci().forEach(s -> modelDuzina.addElement(s));
        lstDuzina.setModel(modelDuzina);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstKolo = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstDuzina = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstPoredak = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Odaberi kolo lige");

        lstKolo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstKoloValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstKolo);

        jLabel2.setText("Odaberi dužinu");

        lstDuzina.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDuzinaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstDuzina);

        jLabel3.setText("Ukupni poredak");

        jScrollPane3.setViewportView(lstPoredak);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane3)))
                .addGap(111, 111, 111))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lstKoloValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstKoloValueChanged
        // TODO add your handling code here:
        
        Kolo odabranoKolo = lstKolo.getSelectedValue();
        
        obradaKolo.setEntitet(odabranoKolo);
        
        if (odabranoKolo == null) {
            return;
        }
        
        Duzina odabranaDuzina = obradaDuzina.getEntitet();
        
        if (odabranaDuzina == null) {
            return;
        }
        
        List<Rezultat> rezultati = obradaRezultat.getPodaci().stream()
                                    .filter(r -> r.getDuzina().equals(odabranaDuzina))
                                    .filter(r -> r.getKolo().equals(odabranoKolo))
                                    .collect(Collectors.toList());
        
        DefaultListModel<String> modelRezultati = new DefaultListModel<>();
        Pomocno.formatirajRezultateZaListu(rezultati).forEach(s -> modelRezultati.addElement(s));
        lstPoredak.setModel(modelRezultati);
        lstPoredak.repaint();
    }//GEN-LAST:event_lstKoloValueChanged

    private void lstDuzinaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDuzinaValueChanged
        // TODO add your handling code here:
        
        Duzina odabranaDuzina = lstDuzina.getSelectedValue();
        
        obradaDuzina.setEntitet(odabranaDuzina);
        
        if (odabranaDuzina == null) {
            return;
        }
        
        Kolo odabranoKolo = obradaKolo.getEntitet();
        
        if (odabranoKolo == null) {
            return;
        }
        
        List<Rezultat> rezultati = obradaRezultat.getPodaci().stream()
                                    .filter(r -> r.getDuzina().getSifra().equals(odabranaDuzina.getSifra()))
                                    .filter(r -> r.getKolo().getSifra().equals(odabranoKolo.getSifra()))
                                    .collect(Collectors.toList());
        
        DefaultListModel<String> modelRezultati = new DefaultListModel<>();
        Pomocno.formatirajRezultateZaListu(rezultati).forEach(s -> modelRezultati.addElement(s));
        lstPoredak.setModel(modelRezultati);
        lstPoredak.repaint();
    }//GEN-LAST:event_lstDuzinaValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRezultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRezultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRezultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRezultat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRezultat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<Duzina> lstDuzina;
    private javax.swing.JList<Kolo> lstKolo;
    private javax.swing.JList<String> lstPoredak;
    // End of variables declaration//GEN-END:variables
}
